# Generated by Django 3.0.5 on 2020-04-16 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_pulished',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 0, 22, 23, 928677), verbose_name='Date Published'),
        ),
    ]
